//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNCSalesforce.Digiturno5Turno {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Turno", Namespace="http://schemas.datacontract.org/2004/07/CIEL.DigiturnoMega.Entidades.Integrador")]
    [System.SerializableAttribute()]
    public partial class Turno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FNCSalesforce.Digiturno5Turno.EstadoTurno EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FNCSalesforce.Digiturno5Turno.Grupo GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTransaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTurnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTurnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FNCSalesforce.Digiturno5Turno.Oficina OficinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FNCSalesforce.Digiturno5Turno.Sala SalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TiempoDesplazamientoSegundosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FNCSalesforce.Digiturno5Turno.EstadoTurno Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FNCSalesforce.Digiturno5Turno.Grupo Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoField, value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTransaccion {
            get {
                return this.IdTransaccionField;
            }
            set {
                if ((this.IdTransaccionField.Equals(value) != true)) {
                    this.IdTransaccionField = value;
                    this.RaisePropertyChanged("IdTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTurno {
            get {
                return this.IdTurnoField;
            }
            set {
                if ((this.IdTurnoField.Equals(value) != true)) {
                    this.IdTurnoField = value;
                    this.RaisePropertyChanged("IdTurno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTurno {
            get {
                return this.NumeroTurnoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTurnoField, value) != true)) {
                    this.NumeroTurnoField = value;
                    this.RaisePropertyChanged("NumeroTurno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FNCSalesforce.Digiturno5Turno.Oficina Oficina {
            get {
                return this.OficinaField;
            }
            set {
                if ((object.ReferenceEquals(this.OficinaField, value) != true)) {
                    this.OficinaField = value;
                    this.RaisePropertyChanged("Oficina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FNCSalesforce.Digiturno5Turno.Sala Sala {
            get {
                return this.SalaField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaField, value) != true)) {
                    this.SalaField = value;
                    this.RaisePropertyChanged("Sala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TiempoDesplazamientoSegundos {
            get {
                return this.TiempoDesplazamientoSegundosField;
            }
            set {
                if ((this.TiempoDesplazamientoSegundosField.Equals(value) != true)) {
                    this.TiempoDesplazamientoSegundosField = value;
                    this.RaisePropertyChanged("TiempoDesplazamientoSegundos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grupo", Namespace="http://schemas.datacontract.org/2004/07/CIEL.DigiturnoMega.Entidades.Integrador")]
    [System.SerializableAttribute()]
    public partial class Grupo : FNCSalesforce.Digiturno5Turno.Basica {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Oficina", Namespace="http://schemas.datacontract.org/2004/07/CIEL.DigiturnoMega.Entidades.Integrador")]
    [System.SerializableAttribute()]
    public partial class Oficina : FNCSalesforce.Digiturno5Turno.Basica {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sala", Namespace="http://schemas.datacontract.org/2004/07/CIEL.DigiturnoMega.Entidades.Integrador")]
    [System.SerializableAttribute()]
    public partial class Sala : FNCSalesforce.Digiturno5Turno.Basica {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoTurno", Namespace="http://schemas.datacontract.org/2004/07/CIEL.DigiturnoMega.Entidades.Integrador.E" +
        "numeracion")]
    public enum EstadoTurno : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NODEFINIDO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ESPERA = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LLAMANDO = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUSPENDIDO = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DISTRAIDO = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATENCION = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CANCELADO = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FINALIZADO = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ABANDONADO = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRANSFERIDO = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Basica", Namespace="http://schemas.datacontract.org/2004/07/CIEL.DigiturnoMega.Entidades.Integrador.B" +
        "ase")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FNCSalesforce.Digiturno5Turno.Oficina))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FNCSalesforce.Digiturno5Turno.Sala))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FNCSalesforce.Digiturno5Turno.Grupo))]
    public partial class Basica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultado", Namespace="http://schemas.datacontract.org/2004/07/CIEL.DigiturnoMega.Entidades.Integrador")]
    [System.SerializableAttribute()]
    public partial class Resultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitosoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso {
            get {
                return this.ExitosoField;
            }
            set {
                if ((this.ExitosoField.Equals(value) != true)) {
                    this.ExitosoField = value;
                    this.RaisePropertyChanged("Exitoso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/CIEL.DigiturnoMega.Entidades.Integrador")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FNCSalesforce.Digiturno5Turno.EstadoUsuario EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FNCSalesforce.Digiturno5Turno.EstadoUsuario Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoUsuario", Namespace="http://schemas.datacontract.org/2004/07/CIEL.DigiturnoMega.Entidades.Integrador.E" +
        "numeracion")]
    public enum EstadoUsuario : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DESCONECTADO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CONECTADO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DISPONIBLE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OCUPADO = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TurnoKiosco", Namespace="http://schemas.datacontract.org/2004/07/CIEL.DigiturnoMega.Entidades.Integrador")]
    [System.SerializableAttribute()]
    public partial class TurnoKiosco : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FNCSalesforce.Digiturno5Turno.EstadoTurnoKiosco EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FNCSalesforce.Digiturno5Turno.Kiosco KioscoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FNCSalesforce.Digiturno5Turno.Turno TurnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FNCSalesforce.Digiturno5Turno.EstadoTurnoKiosco Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoMensaje {
            get {
                return this.EstadoMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoMensajeField, value) != true)) {
                    this.EstadoMensajeField = value;
                    this.RaisePropertyChanged("EstadoMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FNCSalesforce.Digiturno5Turno.Kiosco Kiosco {
            get {
                return this.KioscoField;
            }
            set {
                if ((object.ReferenceEquals(this.KioscoField, value) != true)) {
                    this.KioscoField = value;
                    this.RaisePropertyChanged("Kiosco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FNCSalesforce.Digiturno5Turno.Turno Turno {
            get {
                return this.TurnoField;
            }
            set {
                if ((object.ReferenceEquals(this.TurnoField, value) != true)) {
                    this.TurnoField = value;
                    this.RaisePropertyChanged("Turno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kiosco", Namespace="http://schemas.datacontract.org/2004/07/CIEL.DigiturnoMega.Entidades.Integrador")]
    [System.SerializableAttribute()]
    public partial class Kiosco : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionNoOperativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DireccionEnSalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FNCSalesforce.Digiturno5Turno.EstadoKiosco EstadoActualKioscoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaActualizacionEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HabilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdServidorVideoAtencionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FNCSalesforce.Digiturno5Turno.Sala SalaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionNoOperativo {
            get {
                return this.DescripcionNoOperativoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionNoOperativoField, value) != true)) {
                    this.DescripcionNoOperativoField = value;
                    this.RaisePropertyChanged("DescripcionNoOperativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DireccionEnSala {
            get {
                return this.DireccionEnSalaField;
            }
            set {
                if ((this.DireccionEnSalaField.Equals(value) != true)) {
                    this.DireccionEnSalaField = value;
                    this.RaisePropertyChanged("DireccionEnSala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionIP {
            get {
                return this.DireccionIPField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionIPField, value) != true)) {
                    this.DireccionIPField = value;
                    this.RaisePropertyChanged("DireccionIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FNCSalesforce.Digiturno5Turno.EstadoKiosco EstadoActualKiosco {
            get {
                return this.EstadoActualKioscoField;
            }
            set {
                if ((this.EstadoActualKioscoField.Equals(value) != true)) {
                    this.EstadoActualKioscoField = value;
                    this.RaisePropertyChanged("EstadoActualKiosco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaActualizacionEstado {
            get {
                return this.FechaActualizacionEstadoField;
            }
            set {
                if ((this.FechaActualizacionEstadoField.Equals(value) != true)) {
                    this.FechaActualizacionEstadoField = value;
                    this.RaisePropertyChanged("FechaActualizacionEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Habilitado {
            get {
                return this.HabilitadoField;
            }
            set {
                if ((this.HabilitadoField.Equals(value) != true)) {
                    this.HabilitadoField = value;
                    this.RaisePropertyChanged("Habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdServidorVideoAtencion {
            get {
                return this.IdServidorVideoAtencionField;
            }
            set {
                if ((this.IdServidorVideoAtencionField.Equals(value) != true)) {
                    this.IdServidorVideoAtencionField = value;
                    this.RaisePropertyChanged("IdServidorVideoAtencion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FNCSalesforce.Digiturno5Turno.Sala Sala {
            get {
                return this.SalaField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaField, value) != true)) {
                    this.SalaField = value;
                    this.RaisePropertyChanged("Sala");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoTurnoKiosco", Namespace="http://schemas.datacontract.org/2004/07/CIEL.DigiturnoMega.Entidades.Integrador.E" +
        "numeracion")]
    public enum EstadoTurnoKiosco : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EXITOSO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PENDIENTE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DISTRAIDO = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SINTURNOS = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoKiosco", Namespace="http://schemas.datacontract.org/2004/07/CIEL.DigiturnoMega.Entidades.Integrador")]
    public enum EstadoKiosco : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Libre = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ocupado = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bloqueado = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntesDelSistema.Tipo", Namespace="http://schemas.datacontract.org/2004/07/CIEL.DigiturnoMega.Entidades")]
    public enum EntesDelSistemaTipo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deconocido = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Oficina = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sala = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Grupo = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Servidor = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Selector = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModoEjecucion", Namespace="http://schemas.datacontract.org/2004/07/CIEL.DigiturnoMega.Entidades.Integrador")]
    public enum ModoEjecucion : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Previo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Posterior = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Digiturno5Turno.IServicioTurnos")]
    public interface IServicioTurnos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTurnos/ActualizarEstado", ReplyAction="http://tempuri.org/IServicioTurnos/ActualizarEstadoResponse")]
        FNCSalesforce.Digiturno5Turno.Resultado ActualizarEstado(FNCSalesforce.Digiturno5Turno.Turno turno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTurnos/ActualizarEstado", ReplyAction="http://tempuri.org/IServicioTurnos/ActualizarEstadoResponse")]
        System.Threading.Tasks.Task<FNCSalesforce.Digiturno5Turno.Resultado> ActualizarEstadoAsync(FNCSalesforce.Digiturno5Turno.Turno turno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTurnos/AsignarTurno", ReplyAction="http://tempuri.org/IServicioTurnos/AsignarTurnoResponse")]
        FNCSalesforce.Digiturno5Turno.TurnoKiosco AsignarTurno(FNCSalesforce.Digiturno5Turno.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTurnos/AsignarTurno", ReplyAction="http://tempuri.org/IServicioTurnos/AsignarTurnoResponse")]
        System.Threading.Tasks.Task<FNCSalesforce.Digiturno5Turno.TurnoKiosco> AsignarTurnoAsync(FNCSalesforce.Digiturno5Turno.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTurnos/BalancearTurno", ReplyAction="http://tempuri.org/IServicioTurnos/BalancearTurnoResponse")]
        FNCSalesforce.Digiturno5Turno.Turno BalancearTurno(short idEnteApoyo, FNCSalesforce.Digiturno5Turno.EntesDelSistemaTipo enteSistema, int idJornada, string nombreSPPrioridad, FNCSalesforce.Digiturno5Turno.ModoEjecucion modoEjecucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTurnos/BalancearTurno", ReplyAction="http://tempuri.org/IServicioTurnos/BalancearTurnoResponse")]
        System.Threading.Tasks.Task<FNCSalesforce.Digiturno5Turno.Turno> BalancearTurnoAsync(short idEnteApoyo, FNCSalesforce.Digiturno5Turno.EntesDelSistemaTipo enteSistema, int idJornada, string nombreSPPrioridad, FNCSalesforce.Digiturno5Turno.ModoEjecucion modoEjecucion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioTurnosChannel : FNCSalesforce.Digiturno5Turno.IServicioTurnos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioTurnosClient : System.ServiceModel.ClientBase<FNCSalesforce.Digiturno5Turno.IServicioTurnos>, FNCSalesforce.Digiturno5Turno.IServicioTurnos {
        
        public ServicioTurnosClient() {
        }
        
        public ServicioTurnosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioTurnosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTurnosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTurnosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FNCSalesforce.Digiturno5Turno.Resultado ActualizarEstado(FNCSalesforce.Digiturno5Turno.Turno turno) {
            return base.Channel.ActualizarEstado(turno);
        }
        
        public System.Threading.Tasks.Task<FNCSalesforce.Digiturno5Turno.Resultado> ActualizarEstadoAsync(FNCSalesforce.Digiturno5Turno.Turno turno) {
            return base.Channel.ActualizarEstadoAsync(turno);
        }
        
        public FNCSalesforce.Digiturno5Turno.TurnoKiosco AsignarTurno(FNCSalesforce.Digiturno5Turno.Usuario usuario) {
            return base.Channel.AsignarTurno(usuario);
        }
        
        public System.Threading.Tasks.Task<FNCSalesforce.Digiturno5Turno.TurnoKiosco> AsignarTurnoAsync(FNCSalesforce.Digiturno5Turno.Usuario usuario) {
            return base.Channel.AsignarTurnoAsync(usuario);
        }
        
        public FNCSalesforce.Digiturno5Turno.Turno BalancearTurno(short idEnteApoyo, FNCSalesforce.Digiturno5Turno.EntesDelSistemaTipo enteSistema, int idJornada, string nombreSPPrioridad, FNCSalesforce.Digiturno5Turno.ModoEjecucion modoEjecucion) {
            return base.Channel.BalancearTurno(idEnteApoyo, enteSistema, idJornada, nombreSPPrioridad, modoEjecucion);
        }
        
        public System.Threading.Tasks.Task<FNCSalesforce.Digiturno5Turno.Turno> BalancearTurnoAsync(short idEnteApoyo, FNCSalesforce.Digiturno5Turno.EntesDelSistemaTipo enteSistema, int idJornada, string nombreSPPrioridad, FNCSalesforce.Digiturno5Turno.ModoEjecucion modoEjecucion) {
            return base.Channel.BalancearTurnoAsync(idEnteApoyo, enteSistema, idJornada, nombreSPPrioridad, modoEjecucion);
        }
    }
}
