//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNCSalesforce.InspiraSynapseWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="InspiraSynapseWS.InspiraSynapse")]
    public interface InspiraSynapse {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:InspiraSynapse/SendAppointment", ReplyAction="urn:InspiraSynapse/SendAppointmentResponse")]
        string SendAppointment(string sRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:InspiraSynapse/SendAppointment", ReplyAction="urn:InspiraSynapse/SendAppointmentResponse")]
        System.Threading.Tasks.Task<string> SendAppointmentAsync(string sRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InspiraSynapseChannel : FNCSalesforce.InspiraSynapseWS.InspiraSynapse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InspiraSynapseClient : System.ServiceModel.ClientBase<FNCSalesforce.InspiraSynapseWS.InspiraSynapse>, FNCSalesforce.InspiraSynapseWS.InspiraSynapse {
        
        public InspiraSynapseClient() {
        }
        
        public InspiraSynapseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InspiraSynapseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InspiraSynapseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InspiraSynapseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendAppointment(string sRequest) {
            return base.Channel.SendAppointment(sRequest);
        }
        
        public System.Threading.Tasks.Task<string> SendAppointmentAsync(string sRequest) {
            return base.Channel.SendAppointmentAsync(sRequest);
        }
    }
}
