//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SendPatientDocumentation.FNCESB {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSDigiturnoSoap", Namespace="http://190.144.73.250:9090/")]
    public partial class WSDigiturno : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GenerateTurnOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPatientOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecieveTurnOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTimeDistributionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CallPatientOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSystemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateInspiraObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTodayPatientsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSDigiturno() {
            this.Url = global::SendPatientDocumentation.Properties.Settings.Default.SendPatientDocumentation_FNCESB_WSDigiturno;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GenerateTurnCompletedEventHandler GenerateTurnCompleted;
        
        /// <remarks/>
        public event GetPatientCompletedEventHandler GetPatientCompleted;
        
        /// <remarks/>
        public event RecieveTurnCompletedEventHandler RecieveTurnCompleted;
        
        /// <remarks/>
        public event GetTimeDistributionCompletedEventHandler GetTimeDistributionCompleted;
        
        /// <remarks/>
        public event CallPatientCompletedEventHandler CallPatientCompleted;
        
        /// <remarks/>
        public event UpdateSystemsCompletedEventHandler UpdateSystemsCompleted;
        
        /// <remarks/>
        public event UpdateInspiraObjectCompletedEventHandler UpdateInspiraObjectCompleted;
        
        /// <remarks/>
        public event UpdateAccountCompletedEventHandler UpdateAccountCompleted;
        
        /// <remarks/>
        public event GetTodayPatientsCompletedEventHandler GetTodayPatientsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/GenerateTurn", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerateTurn(string oRequest) {
            object[] results = this.Invoke("GenerateTurn", new object[] {
                        oRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateTurnAsync(string oRequest) {
            this.GenerateTurnAsync(oRequest, null);
        }
        
        /// <remarks/>
        public void GenerateTurnAsync(string oRequest, object userState) {
            if ((this.GenerateTurnOperationCompleted == null)) {
                this.GenerateTurnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateTurnOperationCompleted);
            }
            this.InvokeAsync("GenerateTurn", new object[] {
                        oRequest}, this.GenerateTurnOperationCompleted, userState);
        }
        
        private void OnGenerateTurnOperationCompleted(object arg) {
            if ((this.GenerateTurnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateTurnCompleted(this, new GenerateTurnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/GetPatient", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Digiturno5 GetPatient(string sdocumenttype, string sdocument, string suser, string spassword) {
            object[] results = this.Invoke("GetPatient", new object[] {
                        sdocumenttype,
                        sdocument,
                        suser,
                        spassword});
            return ((Digiturno5)(results[0]));
        }
        
        /// <remarks/>
        public void GetPatientAsync(string sdocumenttype, string sdocument, string suser, string spassword) {
            this.GetPatientAsync(sdocumenttype, sdocument, suser, spassword, null);
        }
        
        /// <remarks/>
        public void GetPatientAsync(string sdocumenttype, string sdocument, string suser, string spassword, object userState) {
            if ((this.GetPatientOperationCompleted == null)) {
                this.GetPatientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPatientOperationCompleted);
            }
            this.InvokeAsync("GetPatient", new object[] {
                        sdocumenttype,
                        sdocument,
                        suser,
                        spassword}, this.GetPatientOperationCompleted, userState);
        }
        
        private void OnGetPatientOperationCompleted(object arg) {
            if ((this.GetPatientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPatientCompleted(this, new GetPatientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/RecieveTurn", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result RecieveTurn(string sTurnResult) {
            object[] results = this.Invoke("RecieveTurn", new object[] {
                        sTurnResult});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void RecieveTurnAsync(string sTurnResult) {
            this.RecieveTurnAsync(sTurnResult, null);
        }
        
        /// <remarks/>
        public void RecieveTurnAsync(string sTurnResult, object userState) {
            if ((this.RecieveTurnOperationCompleted == null)) {
                this.RecieveTurnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecieveTurnOperationCompleted);
            }
            this.InvokeAsync("RecieveTurn", new object[] {
                        sTurnResult}, this.RecieveTurnOperationCompleted, userState);
        }
        
        private void OnRecieveTurnOperationCompleted(object arg) {
            if ((this.RecieveTurnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecieveTurnCompleted(this, new RecieveTurnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/GetTimeDistribution", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Generic[] GetTimeDistribution(string sCost, int iMonth, int iYear) {
            object[] results = this.Invoke("GetTimeDistribution", new object[] {
                        sCost,
                        iMonth,
                        iYear});
            return ((Generic[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTimeDistributionAsync(string sCost, int iMonth, int iYear) {
            this.GetTimeDistributionAsync(sCost, iMonth, iYear, null);
        }
        
        /// <remarks/>
        public void GetTimeDistributionAsync(string sCost, int iMonth, int iYear, object userState) {
            if ((this.GetTimeDistributionOperationCompleted == null)) {
                this.GetTimeDistributionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTimeDistributionOperationCompleted);
            }
            this.InvokeAsync("GetTimeDistribution", new object[] {
                        sCost,
                        iMonth,
                        iYear}, this.GetTimeDistributionOperationCompleted, userState);
        }
        
        private void OnGetTimeDistributionOperationCompleted(object arg) {
            if ((this.GetTimeDistributionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTimeDistributionCompleted(this, new GetTimeDistributionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/CallPatient", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CallPatient(string sRoom, string sPatient, string sTurn, string sDocumentType, string sDocument, string sIsUpdate, string sFloor) {
            this.Invoke("CallPatient", new object[] {
                        sRoom,
                        sPatient,
                        sTurn,
                        sDocumentType,
                        sDocument,
                        sIsUpdate,
                        sFloor});
        }
        
        /// <remarks/>
        public void CallPatientAsync(string sRoom, string sPatient, string sTurn, string sDocumentType, string sDocument, string sIsUpdate, string sFloor) {
            this.CallPatientAsync(sRoom, sPatient, sTurn, sDocumentType, sDocument, sIsUpdate, sFloor, null);
        }
        
        /// <remarks/>
        public void CallPatientAsync(string sRoom, string sPatient, string sTurn, string sDocumentType, string sDocument, string sIsUpdate, string sFloor, object userState) {
            if ((this.CallPatientOperationCompleted == null)) {
                this.CallPatientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallPatientOperationCompleted);
            }
            this.InvokeAsync("CallPatient", new object[] {
                        sRoom,
                        sPatient,
                        sTurn,
                        sDocumentType,
                        sDocument,
                        sIsUpdate,
                        sFloor}, this.CallPatientOperationCompleted, userState);
        }
        
        private void OnCallPatientOperationCompleted(object arg) {
            if ((this.CallPatientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallPatientCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/UpdateSystems", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateSystems(string sappointment, int ientry, int iresult) {
            this.Invoke("UpdateSystems", new object[] {
                        sappointment,
                        ientry,
                        iresult});
        }
        
        /// <remarks/>
        public void UpdateSystemsAsync(string sappointment, int ientry, int iresult) {
            this.UpdateSystemsAsync(sappointment, ientry, iresult, null);
        }
        
        /// <remarks/>
        public void UpdateSystemsAsync(string sappointment, int ientry, int iresult, object userState) {
            if ((this.UpdateSystemsOperationCompleted == null)) {
                this.UpdateSystemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSystemsOperationCompleted);
            }
            this.InvokeAsync("UpdateSystems", new object[] {
                        sappointment,
                        ientry,
                        iresult}, this.UpdateSystemsOperationCompleted, userState);
        }
        
        private void OnUpdateSystemsOperationCompleted(object arg) {
            if ((this.UpdateSystemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSystemsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/UpdateInspiraObject", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateInspiraObject(InspiraTemporal[] linspiratemporal, string sobject) {
            this.Invoke("UpdateInspiraObject", new object[] {
                        linspiratemporal,
                        sobject});
        }
        
        /// <remarks/>
        public void UpdateInspiraObjectAsync(InspiraTemporal[] linspiratemporal, string sobject) {
            this.UpdateInspiraObjectAsync(linspiratemporal, sobject, null);
        }
        
        /// <remarks/>
        public void UpdateInspiraObjectAsync(InspiraTemporal[] linspiratemporal, string sobject, object userState) {
            if ((this.UpdateInspiraObjectOperationCompleted == null)) {
                this.UpdateInspiraObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateInspiraObjectOperationCompleted);
            }
            this.InvokeAsync("UpdateInspiraObject", new object[] {
                        linspiratemporal,
                        sobject}, this.UpdateInspiraObjectOperationCompleted, userState);
        }
        
        private void OnUpdateInspiraObjectOperationCompleted(object arg) {
            if ((this.UpdateInspiraObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateInspiraObjectCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/UpdateAccount", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateAccount(string sDocument, string sDocumentType, string[] aResponse) {
            this.Invoke("UpdateAccount", new object[] {
                        sDocument,
                        sDocumentType,
                        aResponse});
        }
        
        /// <remarks/>
        public void UpdateAccountAsync(string sDocument, string sDocumentType, string[] aResponse) {
            this.UpdateAccountAsync(sDocument, sDocumentType, aResponse, null);
        }
        
        /// <remarks/>
        public void UpdateAccountAsync(string sDocument, string sDocumentType, string[] aResponse, object userState) {
            if ((this.UpdateAccountOperationCompleted == null)) {
                this.UpdateAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAccountOperationCompleted);
            }
            this.InvokeAsync("UpdateAccount", new object[] {
                        sDocument,
                        sDocumentType,
                        aResponse}, this.UpdateAccountOperationCompleted, userState);
        }
        
        private void OnUpdateAccountOperationCompleted(object arg) {
            if ((this.UpdateAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAccountCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://190.144.73.250:9090/GetTodayPatients", RequestNamespace="http://190.144.73.250:9090/", ResponseNamespace="http://190.144.73.250:9090/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTodayPatients(string sPatients) {
            object[] results = this.Invoke("GetTodayPatients", new object[] {
                        sPatients});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTodayPatientsAsync(string sPatients) {
            this.GetTodayPatientsAsync(sPatients, null);
        }
        
        /// <remarks/>
        public void GetTodayPatientsAsync(string sPatients, object userState) {
            if ((this.GetTodayPatientsOperationCompleted == null)) {
                this.GetTodayPatientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTodayPatientsOperationCompleted);
            }
            this.InvokeAsync("GetTodayPatients", new object[] {
                        sPatients}, this.GetTodayPatientsOperationCompleted, userState);
        }
        
        private void OnGetTodayPatientsOperationCompleted(object arg) {
            if ((this.GetTodayPatientsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTodayPatientsCompleted(this, new GetTodayPatientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://190.144.73.250:9090/")]
    public partial class Digiturno5 {
        
        private PatientCiel oPatientField;
        
        private Result oResultField;
        
        /// <remarks/>
        public PatientCiel oPatient {
            get {
                return this.oPatientField;
            }
            set {
                this.oPatientField = value;
            }
        }
        
        /// <remarks/>
        public Result oResult {
            get {
                return this.oResultField;
            }
            set {
                this.oResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://190.144.73.250:9090/")]
    public partial class PatientCiel {
        
        private int iplanField;
        
        private int iunitField;
        
        private int iattendanceField;
        
        private string sfirstnameField;
        
        private string ssecondnameField;
        
        private string sfirstsurnameField;
        
        private string ssecondsurnameField;
        
        /// <remarks/>
        public int iplan {
            get {
                return this.iplanField;
            }
            set {
                this.iplanField = value;
            }
        }
        
        /// <remarks/>
        public int iunit {
            get {
                return this.iunitField;
            }
            set {
                this.iunitField = value;
            }
        }
        
        /// <remarks/>
        public int iattendance {
            get {
                return this.iattendanceField;
            }
            set {
                this.iattendanceField = value;
            }
        }
        
        /// <remarks/>
        public string sfirstname {
            get {
                return this.sfirstnameField;
            }
            set {
                this.sfirstnameField = value;
            }
        }
        
        /// <remarks/>
        public string ssecondname {
            get {
                return this.ssecondnameField;
            }
            set {
                this.ssecondnameField = value;
            }
        }
        
        /// <remarks/>
        public string sfirstsurname {
            get {
                return this.sfirstsurnameField;
            }
            set {
                this.sfirstsurnameField = value;
            }
        }
        
        /// <remarks/>
        public string ssecondsurname {
            get {
                return this.ssecondsurnameField;
            }
            set {
                this.ssecondsurnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://190.144.73.250:9090/")]
    public partial class InspiraTemporal {
        
        private long lconsecutivoField;
        
        private string scodField;
        
        private string snombreField;
        
        private string sparametro1Field;
        
        private string sparametro2Field;
        
        private string stablaField;
        
        private int iparametro3Field;
        
        private int iidField;
        
        private char cactivoField;
        
        private int isincronizadoField;
        
        private string santeriorField;
        
        private int iedicionField;
        
        /// <remarks/>
        public long lconsecutivo {
            get {
                return this.lconsecutivoField;
            }
            set {
                this.lconsecutivoField = value;
            }
        }
        
        /// <remarks/>
        public string scod {
            get {
                return this.scodField;
            }
            set {
                this.scodField = value;
            }
        }
        
        /// <remarks/>
        public string snombre {
            get {
                return this.snombreField;
            }
            set {
                this.snombreField = value;
            }
        }
        
        /// <remarks/>
        public string sparametro1 {
            get {
                return this.sparametro1Field;
            }
            set {
                this.sparametro1Field = value;
            }
        }
        
        /// <remarks/>
        public string sparametro2 {
            get {
                return this.sparametro2Field;
            }
            set {
                this.sparametro2Field = value;
            }
        }
        
        /// <remarks/>
        public string stabla {
            get {
                return this.stablaField;
            }
            set {
                this.stablaField = value;
            }
        }
        
        /// <remarks/>
        public int iparametro3 {
            get {
                return this.iparametro3Field;
            }
            set {
                this.iparametro3Field = value;
            }
        }
        
        /// <remarks/>
        public int iid {
            get {
                return this.iidField;
            }
            set {
                this.iidField = value;
            }
        }
        
        /// <remarks/>
        public char cactivo {
            get {
                return this.cactivoField;
            }
            set {
                this.cactivoField = value;
            }
        }
        
        /// <remarks/>
        public int isincronizado {
            get {
                return this.isincronizadoField;
            }
            set {
                this.isincronizadoField = value;
            }
        }
        
        /// <remarks/>
        public string santerior {
            get {
                return this.santeriorField;
            }
            set {
                this.santeriorField = value;
            }
        }
        
        /// <remarks/>
        public int iedicion {
            get {
                return this.iedicionField;
            }
            set {
                this.iedicionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://190.144.73.250:9090/")]
    public partial class Generic {
        
        private int iidField;
        
        private string snameField;
        
        private string scodeField;
        
        private string sfilterField;
        
        private System.DateTime dtDateField;
        
        private string sextra1Field;
        
        private double dextra2Field;
        
        /// <remarks/>
        public int iid {
            get {
                return this.iidField;
            }
            set {
                this.iidField = value;
            }
        }
        
        /// <remarks/>
        public string sname {
            get {
                return this.snameField;
            }
            set {
                this.snameField = value;
            }
        }
        
        /// <remarks/>
        public string scode {
            get {
                return this.scodeField;
            }
            set {
                this.scodeField = value;
            }
        }
        
        /// <remarks/>
        public string sfilter {
            get {
                return this.sfilterField;
            }
            set {
                this.sfilterField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dtDate {
            get {
                return this.dtDateField;
            }
            set {
                this.dtDateField = value;
            }
        }
        
        /// <remarks/>
        public string sextra1 {
            get {
                return this.sextra1Field;
            }
            set {
                this.sextra1Field = value;
            }
        }
        
        /// <remarks/>
        public double dextra2 {
            get {
                return this.dextra2Field;
            }
            set {
                this.dextra2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://190.144.73.250:9090/")]
    public partial class Result {
        
        private int iresultField;
        
        private string smessageField;
        
        /// <remarks/>
        public int iresult {
            get {
                return this.iresultField;
            }
            set {
                this.iresultField = value;
            }
        }
        
        /// <remarks/>
        public string smessage {
            get {
                return this.smessageField;
            }
            set {
                this.smessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GenerateTurnCompletedEventHandler(object sender, GenerateTurnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateTurnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateTurnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetPatientCompletedEventHandler(object sender, GetPatientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPatientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPatientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Digiturno5 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Digiturno5)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void RecieveTurnCompletedEventHandler(object sender, RecieveTurnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecieveTurnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecieveTurnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetTimeDistributionCompletedEventHandler(object sender, GetTimeDistributionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTimeDistributionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTimeDistributionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Generic[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Generic[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CallPatientCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UpdateSystemsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UpdateInspiraObjectCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UpdateAccountCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetTodayPatientsCompletedEventHandler(object sender, GetTodayPatientsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTodayPatientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTodayPatientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591